import "./globals.css";
//componets
import Header from "@/components/Header";
import { JetBrains_Mono } from "next/font/google";

const jetBrainsMono = JetBrains_Mono({subsets: ["latin"] ,
  Weight:['100','200','300','400','500','600','700','800'],
  Variable:"--font-jetbrainsMono",

})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
    
      <body className = {jetBrainsMono.Variable}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
